const app=document.querySelector('#app');
const api=async(path,options={})=>{const response=await fetch('/api'+path,{headers:{'Content-Type':'application/json'},...options});if(!response.ok)throw new Error((await response.json()).detail||'Request failed');return response.json()};
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const text=value=>esc(value).replace(/\n\n/g,'</p><p>');
const title=value=>esc(value).replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
window.addEventListener('hashchange',route);window.addEventListener('DOMContentLoaded',route);
async function route(){try{const path=location.hash.slice(1)||'/';if(path==='/')return dashboard();if(path==='/topics')return topics();if(path==='/review')return review();if(path.startsWith('/topics/'))return topic(path.split('/')[2]);app.innerHTML='<div class="empty"><h1>Page not found</h1></div>'}catch(error){app.innerHTML=`<div class="empty error"><h2>Something went wrong</h2><p>${esc(error.message)}</p></div>`}}
async function dashboard(){const s=await api('/progress/summary');app.innerHTML=`<section class="hero"><div><div class="eyebrow">Your learning environment</div><h1>Knowledge that returns.</h1><p class="lead">Build durable machine-learning intuition through active recall and connected concept refreshers.</p><div class="actions"><a class="button" href="#/review">Start daily review · ${s.due_today}</a><a class="button secondary" href="#/topics">Browse knowledge</a></div></div><div class="card"><div class="eyebrow">Today</div><p><strong>${s.due_today}</strong> questions are ready for review.</p><p class="muted">Forgetting is expected. This is where understanding comes back.</p></div></section><section class="grid"><div class="card stat"><span class="muted">Topics</span><strong>${s.total_topics}</strong></div><div class="card stat"><span class="muted">Questions</span><strong>${s.total_questions}</strong></div><div class="card stat"><span class="muted">Reviews completed</span><strong>${s.total_reviews}</strong></div></section><section class="section"><div class="eyebrow">Focus</div><h2>Weak topics</h2>${s.weak_topics.length?s.weak_topics.map(t=>`<p class="weak"><a href="#/topics/${t.id}">${esc(t.title)}</a> · ${t.count} difficult review${t.count>1?'s':''}</p>`).join(''):'<p class="muted">No weak topics yet. Rate a review honestly and this area will adapt.</p>'}</section>`}
async function topics(){const items=await api('/topics');app.innerHTML=`<div class="eyebrow">Knowledge base</div><h1>Topics</h1><p class="lead">Connected explanations, from quick recall to deeper understanding.</p><input class="search" type="search" placeholder="Search topics or tags…" aria-label="Search topics"><div class="grid" id="topic-grid">${topicCards(items)}</div>`;document.querySelector('.search').addEventListener('input',async e=>document.querySelector('#topic-grid').innerHTML=topicCards(await api('/topics?search='+encodeURIComponent(e.target.value))))}
function topicCards(items){return items.map(t=>`<a class="card topic-card" href="#/topics/${t.id}"><div class="eyebrow">${title(t.category)} · ${title(t.difficulty)}</div><h2>${esc(t.title)}</h2><p class="muted">${esc(t.one_sentence_summary)}</p></a>`).join('')||'<p class="muted">No matching topics.</p>'}
async function topic(id){const t=await api('/topics/'+id);const arch=t.architecture;app.innerHTML=`<article><div class="topic-head"><a class="text-link" href="#/topics">← All topics</a><div class="eyebrow" style="margin-top:24px">${title(t.category)} · ${title(t.difficulty)}</div><h1>${esc(t.title)}</h1><p class="lead">${esc(t.one_sentence_summary)}</p>${(t.tags||[]).map(x=>`<span class="pill">${esc(x)}</span>`).join('')}</div><section class="card section"><div class="eyebrow">20–60 seconds</div><h2>Quick recall</h2><p>${text(t.quick_recall)}</p></section><section class="section"><div class="eyebrow">Core understanding</div><h2>The central idea</h2><p>${text(t.core_explanation)}</p></section>${t.why_it_matters?`<section class="section"><h2>Why it matters</h2><p>${text(t.why_it_matters)}</p></section>`:''}${arch?`<section class="section"><div class="eyebrow">Architecture</div><h2>Residual block</h2><p>${text(arch.description)}</p>${(arch.images||[]).map(i=>`<figure class="architecture"><img src="/${esc(i.path)}" alt="${esc(i.caption)}"><figcaption><strong>${esc(i.caption)}</strong><br><span class="muted">${esc(i.source_title)} · ${esc(i.license)}</span></figcaption></figure>`).join('')}<h3>How to read this diagram</h3><ol>${(arch.how_to_read||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ol></section>`:''}<section class="section"><h2>Related concepts</h2>${t.related_topic_details.map(x=>`<a class="pill" href="#/topics/${x.id}">${esc(x.title)}</a>`).join('')}</section><section class="section"><h2>Sources</h2>${(t.sources||[]).map(s=>`<p class="source"><a class="text-link" href="${esc(s.url)}" target="_blank" rel="noreferrer">${esc(s.title)}</a><br><span class="muted">${title(s.type)}</span></p>`).join('')}</section></article>`}
let queue=[],index=0;
async function review(){queue=await api('/review/due');index=0;renderQuestion()}
function renderQuestion(){if(index>=queue.length){app.innerHTML='<div class="empty"><div class="eyebrow">Session complete</div><h1>You’re caught up.</h1><p class="lead">The schedule will bring each idea back when it is useful.</p><a class="button" href="#/">See progress</a></div>';return}const q=queue[index],t=q.concept_refresher;app.innerHTML=`<section class="review"><div class="eyebrow">Question ${index+1} / ${queue.length} · ${title(t.category)} · ${title(q.difficulty)}</div><div class="question">${esc(q.question)}</div><textarea rows="6" placeholder="Explain it in your own words…" aria-label="Your answer"></textarea><div class="actions"><button id="reveal">Show answer</button></div><div id="answer"></div></section>`;document.querySelector('#reveal').onclick=()=>{const answer=document.querySelector('textarea').value;document.querySelector('#reveal').remove();document.querySelector('textarea').disabled=true;document.querySelector('#answer').innerHTML=`<div class="answer"><div class="eyebrow">Direct answer</div><p><strong>${text(q.short_answer)}</strong></p><h3>Expanded explanation</h3><p>${text(q.expanded_answer)}</p><h3>Key points</h3><ul class="keypoints">${q.key_points.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><div class="card section"><div class="eyebrow">Concept refresher · ${esc(t.title)}</div><h2>${esc(t.one_sentence_summary)}</h2><p>${text(t.quick_recall)}</p><a class="text-link" href="#/topics/${t.id}">Open full topic →</a></div><h3>How well did you know this?</h3><div class="actions rating">${['again','hard','good','easy'].map(r=>`<button data-rating="${r}">${title(r)}</button>`).join('')}</div></div>`;document.querySelectorAll('[data-rating]').forEach(b=>b.onclick=async()=>{document.querySelectorAll('[data-rating]').forEach(x=>x.disabled=true);await api('/review/'+q.id,{method:'POST',body:JSON.stringify({rating:b.dataset.rating,answer})});index++;renderQuestion()})}}
